### ISSUE TITLE
Kurz Geschichte über den Bot

### ISSUE THREAD

**Issue by ubeganov** [ID-Start-Winter22/Barty#25]
- [x] Eine Geschichte über den Bot ist entwickelt. 
- [x] Die Geschichte befindet sich im Wiki.

**Comment by JuliaOberhauser** [comment]
Ich hab eine Geschichte über Barty geschrieben und Sie zum Wiki hinzugefügt. @tanzendetatjana müsste noch eine Illustration entwerfen, wenn wir eine haben wollen. [Hier](https://github.com/ID-Start-Winter22/Barty/wiki/Geschichte) könnt ihr euch die Geschichte anschauen.

**Comment by JuliaOberhauser** [comment]
Haben uns aus Zeit Gründen, gegen eine Illustration für die Geschichte entschieden
