### ISSUE TITLE
Conversation Design Canvas

### ISSUE THREAD

**Issue by luaxv0** [ID-Start-Winter22/Barty#27]
- [x] Conversation Design Canvas ist ausgefüllt
- [x] Worksheet befindet sich im Wiki
- [x] Worksheet ist im Issue verlinkt

**Comment by JuliaOberhauser** [comment]
Hab das Conversation Design Canvas ausgefüllt und in der Wiki hinzugefüht.
https://miro.com/app/board/uXjVP-pEp8g=/?moveToWidget=3458764540976486075&cot=14

**Comment by ubeganov** [comment]
@tanzendetatjana kannst du dir das mal anschauen? (review)
