### ISSUE TITLE
Rasa Stories hinzufügen

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#28]
- [x] Jeden Pfad finden
- [x] Checkpoints erstellen überall, wo etwas doppelt vorkommt
- [x] Storys schreiben

**Comment by tanzendetatjana** [comment]
Die Pfade, vom Dialog wurden geteilt, es gibt insgesamt 50 Pfade

**Comment by tanzendetatjana** [comment]
Ein Checkpoint vom Anfang wurde erstellt

**Comment by tanzendetatjana** [comment]
Die Storys wurden geschrieben

**Comment by tanzendetatjana** [comment]
Ich würde bei Sprint 2 versuchen, den Code zu verkürzen

**Comment by tanzendetatjana** [comment]
@ubeganov Kannst du meine Storys reviewn

**Comment by ubeganov** [comment]
@tanzendetatjana später optimieren, passt aber für diesen Sprint. Danke für die Mühe :)
