### ISSUE TITLE
NLU's angeben

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#29]
- [x] Intents sind erweitert
- [x] Freunde befragt was sie angeben würden
- [x] mehr Intents hinzugefügt

**Comment by ubeganov** [comment]
@tanzendetatjana bitte die AKs angeben, evtl. eine kleine Beschreibung hinzufügen :) danke

**Comment by tanzendetatjana** [comment]
Ich habe die ersten Intens die mir eingefallen sind aufgeschrieben

**Comment by tanzendetatjana** [comment]
Habe eine Demo Version über Voiceflow erstellt und diese den anderen Kommilitonen gegeben, so konnte ich sehen, was sie beim Chatbot eingeben würden und konnte es dann bei den Intens weiter schreiben

**Comment by tanzendetatjana** [comment]
Ich habe nun alle Intents himzugefügt

**Comment by tanzendetatjana** [comment]
@ubeganov Könntest du ein kleines Review geben, bitte?

**Comment by ubeganov** [comment]
@tanzendetatjana passt, reichhaltige Intents vorhanden.
