### ISSUE TITLE
Look & Feel (Iteration)

### ISSUE THREAD

**Issue by ubeganov** [ID-Start-Winter22/Barty#32]
- [x] Neue Icons sind hinzugefügt. 
- [x] Neue Namen sind hinzugefügt.
- [x] Die Seite für Look & Feel ist erstellt.
- [x] Die Seite für Look & Feel ist formatiert. 
- [x] Link zur Seite befindet sich im Kommentar.

**Comment by ubeganov** [comment]
@JuliaOberhauser bitte die Seite formatieren wenn du Zeit hast, ein paar neue Namen wären auch gut. Danke :)

**Comment by tanzendetatjana** [comment]
Der Link zu der Seite ["Look and Feel"](https://github.com/ID-Start-Winter22/Barty/wiki/Iterieren) findet ihr da.

**Comment by ubeganov** [comment]
@tanzendetatjana @JuliaOberhauser ich habe die Seite gecheckt. Alles passt, danke :)
