### ISSUE TITLE
Chatbot Dialoge

### ISSUE THREAD

**Issue by ubeganov** [ID-Start-Winter22/Barty#33]
- [x] Dialoge entsprechen dem Character des Chatbots.
- [x] Dialoge sind für verschiedene Situationen erstellt.
- [x] Link zum Voiceflow befindet sich im Wiki und im Kommentar.

**Comment by tanzendetatjana** [comment]
Die Dialoge wurden an den Chatbot angepasst. Lustig, gesprächig und freundlich sind die wichtigsten Anhaltspunkte dabei.

**Comment by tanzendetatjana** [comment]
Die Dialoge sind für mehrere Situationen erstellt. Sowohl für wenn man ein zufälliges Mischgetränk haben möchte. Als auch wenn man ein bestimmten Namen hat den man heraus finden möchte. Aber auch Cocktail Empfehlungen . Der Link wird in Kürze hochgeladen

**Comment by tanzendetatjana** [comment]
Meine Dialoggestaltung ist Fertig und ich habe es auf der Wiki Seite verlink, sowohl habe ich noch eine kurze Beschreibung reingepackt und Bilder von Voiceflow rein gestellt. 
[Bitte klicke hier um das anzuschauen](https://github.com/ID-Start-Winter22/Barty/wiki/Dialoggestaltung)
@ubeganov, @JuliaOberhauser Bitte bestätigt, das alles für euch in Ordnung ist.

**Comment by ubeganov** [comment]
@tanzendetatjana kannst du die Liste in Voiceflow umbennen, sodass es nicht "Untitled" ist?  Ansonsten passt alles.

**Comment by tanzendetatjana** [comment]
@ubeganov Hab es gemacht, nun heißt es Barty. Danke für den Hinweis.
