### ISSUE TITLE
Rasa Actions implementierung 

### ISSUE THREAD

**Issue by ubeganov** [ID-Start-Winter22/Barty#34]
- [x] Action für Random Cocktail ist implementiert.
- [x] Action für Filter Cocktail ist implementiert.
- [x] Action für Find Recipe ist implementiert.
- [x] Action für Filter Recipe (alcoholic/non-alcoholic) ist implementiert.

**Comment by tanzendetatjana** [comment]
@ubeganov Könntest du bitte bei der Seite ["Dokumentation der Issues"](https://github.com/ID-Start-Winter22/Barty/wiki/Dokumentation-der-Issues) deine Actions genauer zusammen fassen, hab ein wenig bei dir gemacht, du musst den Rest machen.

**Comment by ubeganov** [comment]
Ich habe Actions für Zufallscocktail, Rezept suchen und Rezept filtern (alkoholisch/alkoholfrei) implementiert. Benötige aber Hilfe bei der Überprüfung des gesamtes Codes und Messages in den Actions, sowie bei der Implementierung von Filter Cocktail.
