### ISSUE TITLE
Dokumentation zu Sprint 1 

### ISSUE THREAD

**Issue by ubeganov** [ID-Start-Winter22/Barty#35]
- [x] eine PDF-Datei ist für die Arbeit aus dem Design Bereich erstellt.
- [x] Die Datei befindet sich im Wiki.
- [x] Der Link (bzw. die Datei) sind im Kommentar verlinkt.

**Comment by ubeganov** [comment]
@JuliaOberhauser @tanzendetatjana @Lin-creator - wer kann das übernehmen? 

Bitte Bescheid im Kommentar geben und sich als Assignee eintragen.

Danke :)

**Comment by JuliaOberhauser** [comment]
Kann ich gerne machen :)

**Comment by ubeganov** [comment]
@JuliaOberhauser update?

**Comment by tanzendetatjana** [comment]
Ich hab das Sprint Review erstellt und auf der Wiki verlinkt.
https://github.com/ID-Start-Winter22/Barty/wiki/Sprint-1-Review
@ubeganov, @JuliaOberhauser hat das hier hoch geladen und auf einem anderen Issue
