### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#42]
- [x] Finde 3 Personen, die zu der Zielgruppe passen (@JuliaOberhauser )
- [x] Teste verschiedene Funktionen mit Barty
- [x] Dokumentiere diese Ergebnisse
- [x] Erledige das Miro Board
- [x] Erstelle eine Seite auf der Wiki namens User Testing
- [x] Dokumentier alles auf der Wiki Seite
- [x] (@ubeganov) Schaut es sich dann an, wenn es fertig ist

**Comment by JuliaOberhauser** [comment]
Hab die Personen rausgesucht und meinen teil auf der wiki seite dokumentiert

**Comment by tanzendetatjana** [comment]
Danke @JuliaOberhauser Ich habe näheres zu den Personen geschrieben und die in Persönlichkeiten eingeteilt und habe auch schon einige Sachen dokumentiert.

**Comment by tanzendetatjana** [comment]
Mir fehlt nur noch das Miroboard

**Comment by tanzendetatjana** [comment]
Das Miroboard wurde auch ausgefüllt

**Comment by tanzendetatjana** [comment]
Die Seite zum Usability Testing findet ihr [hier](https://github.com/ID-Start-Winter22/Barty/wiki/Usability-Testing). Da ist auch das Miro Board verlinkt. @ubeganov Bitte kontrolliere, ob da alles in Ordnung ist.

**Comment by ubeganov** [comment]
@tanzendetatjana hast du das Miro Board verlinkt? Bei mir funktioniert der Link nicht. Ansonsten ist alles in Ordnung. Gut gemacht (die Illustrationen auch😊)

**Comment by tanzendetatjana** [comment]
Funktioniert es jetzt @ubeganov?
