### ISSUE TITLE
Actions schreiben

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#43]
- [x] (@ubeganov ) Bitte schreib eine Action, die nach den verschieden Geschmacksrichtungen filtriert.
- [x] (@JuliaOberhauser) Bitte schreib eine Action, die nach Alkohol und nicht Alkohol filtriert.
- [x] Zeigt mir (@tanzendetatjana) am Ende alle und ich überprüfe es

**Comment by JuliaOberhauser** [comment]
Hab einen Code zu den Actions geschrieben und Una geschickt

**Comment by ubeganov** [comment]
@tanzendetatjana code ist im test branch, danke @Lin-creator und @JuliaOberhauser für die Unterstützung :)

**Comment by tanzendetatjana** [comment]
Ja die Actions sind gut geschrieben. Leicht verständlich und strukturiert.
