### ISSUE TITLE
Digitales Zuhause

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#44]
- [x] @ubeganov Bitte erstelle ein Poster, das Barty und seine Arbeitsumgebung gut zeigt
- [x] Beachte, dass die Farben von Barty verwendet werden
- [x] Lad das Poster hoch
- [x] Verlink es dann in dem Issue 
- [x] Und Erstelle eine Wiki Seite dafür
- [x] Zeig es mir (@tanzendetatjana) dann am Ende und ich überprüfe alles

**Comment by ubeganov** [comment]
@tanzendetatjana die Seite kann man [hier](https://github.com/ID-Start-Winter22/Barty/wiki/digitales-Zuhause) finden.

**Comment by tanzendetatjana** [comment]
Ich habe die Seite gefunden und finde das Plakat gut. Ich mag den Retro Stil bei der Schrift. Daumen hoch. @ubeganov
