### ISSUE TITLE
Dialog iterieren

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#45]
- [x] Evaluiere die Aussagen im User Testing 
- [x] Iteriere den Dialog beim Chatbot nach der Kritik beim User Testing
- [x] Erstelle dazu eine Seite bei der Wiki
- [x] Dokumentiere dies
- [ ] (@ubeganov) Am Ende wenn es gemacht wurde, bitte prüf ob alles funktioniert hat.

**Comment by tanzendetatjana** [comment]
Ich habe beim User Testing heraus gefunden, dass beim Design alles stimmt. Das einzige was kritisiert wurde war der Dialog mit den zu vielen Funktionen

**Comment by tanzendetatjana** [comment]
Ich habe iteriert und es bei der Wiki dokumentiert. [Klick hier um das zu sehen](https://github.com/ID-Start-Winter22/Barty/wiki/Iterieren-Look&Feell)

**Comment by tanzendetatjana** [comment]
@ubeganov Kannst du es kontrollieren und wenn alles passt den Issue closen.

**Comment by ubeganov** [comment]
@tanzendetatjana falscher Link für die Wiki Seite.

**Comment by tanzendetatjana** [comment]
Oh ja das war der falsche link hier ist der richtige :)))[hier](https://github.com/ID-Start-Winter22/Barty/wiki/Iterieren-Look&Feel)
