### ISSUE TITLE
Dokumentiere die Issues

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#47]
- [x] Erstelle eine Seite bei der Wiki
- [x] Dokumentiere diese Issues und beschreibe, was wo gemacht wurde
- [x] Verlink diese dann hier
- [ ] Am Ende gehe ich (@tanzendetatjana ) alles durch

**Comment by JuliaOberhauser** [comment]
@tanzendetatjana das kann ich gerne übernehmen

**Comment by JuliaOberhauser** [comment]
Hab alle Issues dokumentiert @tanzendetatjana kannst du dir [hier](https://github.com/ID-Start-Winter22/Barty/wiki/Dokumentation-der-Issues-(Sprint-2)) anschauen.

Ich füge morgen bei den Issues die programmieren beinhalten, die passenden Stellen im Code hinzu

**Comment by JuliaOberhauser** [comment]
@tanzendetatjana kannst du bitte drüber schauen ob das soweit passt. Den Code fürg ich dann noch hinzu wenn ihn linus gepusht hat

**Comment by tanzendetatjana** [comment]
Bis jetzt passt alles und ich finde es ist gut gemacht. Ich schließe den Issue.
