### ISSUE TITLE
Domain, NLU's und Stories

### ISSUE THREAD

**Issue by tanzendetatjana** [ID-Start-Winter22/Barty#48]
- [x] (@ubeganov @JuliaOberhauser) Bitt bearbeitet die Stories neu nach dem Dialog der angepasst wurde.
- [x] Schreibt dann das gesagt vom Chatbot in die Domain.
- [x] Und das was der User sagt in die NLU oder in die Actions, was euch besser passt.
- [x] Am Ende kontrolliere ich (@tanzendetatjana) es.

**Comment by ubeganov** [comment]
@tanzendetatjana bitte review

**Comment by tanzendetatjana** [comment]
HAb alles angeschaut es sieht gut aus auch wenn eine Story nicht funktioniert. Aber da gibt es keinen erklärenden Grund
