### ISSUE TITLE
Sprint Review erstellen

### ISSUE THREAD

**Issue by ghost** [ID-Start-Winter22/Barty#49]
- [x] Präsentation für Sprint Review erstellen
- [x] Präsentation hochladen
- [x] Präsentation in der Wiki hochladen

**Comment by JuliaOberhauser** [comment]
@tanzendetatjana könntest du das bitte übernehmen

**Comment by JuliaOberhauser** [comment]
Hab die [PDF](https://github.com/ID-Start-Winter22/Barty/blob/d0152f04cbdc27f3a58ce480a6d901a408692d58/Sprint%20Review%202.pdf) erstellt und auf der [Wiki](https://github.com/ID-Start-Winter22/Barty/wiki/Sprint-2-Review) hochgeladen
